version: '2'
services:
    rock-app:
        image: rock
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rock-mysql:3306/rock?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rock-mysql:
        extends:
            file: mysql.yml
            service: rock-mysql
